apiVersion: v1
kind: Secret
metadata:
  name: deployer
  annotations:
    kubernetes.io/service-account.name: deployer
data:
  ca.crt: {{ .Values.global.jwtCertBase64 }}
  token: {{ .Values.global.jwtBase64 }}
type: kubernetes.io/service-account-token
