apiVersion: v1
kind: Secret
metadata:
  name: deployer
  namespace: default
  annotations:
    kubernetes.io/service-account.name: deployer
data:
  token: {{ .Values.global.jwtBase64 }}
type: kubernetes.io/service-account-token
