apiVersion: v1
kind: Secret
metadata:
  name: deployer
  namespace: default
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.k8CertBase64 }}
  tls.key: {{ .Values.global.k8KeyBase64 }}
