apiVersion: v1
kind: Secret
metadata:
  name: deployer
  namespace: default
  annotations:
    kubernetes.io/service-account.name: default
data:
  token: {{ .Values.global.env.K8_TOKEN }}
type: kubernetes.io/service-account-token
