apiVersion: v1
kind: Secret
metadata:
  name: deployer
  annotations:
    kubernetes.io/service-account.name: deployer
data:
  token: {{ .Values.global.deployerJTWBase64 }}
type: kubernetes.io/service-account-token
