replicas: 1

port: 80

env:
  prod:
    image: flowmapp/maestro-front
    host: maestro.flowmapp.com
    secretName: tls-flowmapp-wildcard
  staging:
    image: flowmapp/maestro-front-staging
    host: maestro.staging.flowmapp.com
    secretName: tls-front
  dev:
    image: flowmapp/maestro-front-dev
    host: maestro.dev.flowmapp.com
    secretName: tls-front
