replicas: 1

port: 80

annotations:
  cert-manager.io/cluster-issuer: letsencrypt

image:
  prod: flowmapp/maestro-front
  staging: flowmapp/maestro-front-staging
  dev: flowmapp/maestro-front-dev

host:
  prod: maestro.flowmapp.com
  staging: maestro.staging.flowmapp.com
  dev: maestro.dev.flowmapp.com

secretName:
  prod: tls-flowmapp-wildcard
  staging: tls-front
  dev: tls-front
