global:
  currentEnv: prod
  secretNamespaces:
    - app
    - maestro
  env:
    prod:
      ip: 5.161.236.111
    staging:
      ip: 78.47.43.69
    dev:
      ip: 88.198.75.57
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - ca-worker-1
              - ca-worker-2
              - us-worker-1
              - us-worker-2
              - dev
              - staging
