global:
  currentEnv: prod
  secretNamespaces:
    - app
    - maestro
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - ca-worker-1
              - ca-worker-2
              - us-worker-1
              - us-worker-2
              - dev
              - staging
