replicas: 1

port: 4040

image:
  prod: flowmapp/maestro-back
  staging: flowmapp/maestro-back-staging
  dev: flowmapp/maestro-back-dev

host:
  prod: api.maestro.flowmapp.com
  staging: api.maestro.staging.flowmapp.com
  dev: api.maestro.dev.flowmapp.com

secretName:
  prod: tls-back
  staging: tls-back
  dev: tls-back
