replicas: 1

port: 4040

annotations:
  cert-manager.io/cluster-issuer: letsencrypt

image:
  prod: flowmapp/maestro-back
  staging: flowmapp/maestro-back-staging
  dev: flowmapp/maestro-back-dev

host:
  prod: apimaestro.flowmapp.com
  staging: api.maestro.staging.flowmapp.com
  dev: api.maestro.dev.flowmapp.com

secretName:
  prod: tls-flowmapp-wildcard
  staging: tls-back
  dev: tls-back
