replicas: 1

port: 4040

env:
  prod:
    image: flowmapp/maestro-back
    host: api.maestro.flowmapp.com
    secretName: tls-back
  staging:
    image: flowmapp/maestro-back-staging
    host: api.maestro.staging.flowmapp.com
    secretName: tls-back
  dev:
    image: flowmapp/maestro-back-dev
    host: api.maestro.dev.flowmapp.com
    secretName: tls-back
