replicas: 1

port: 11443

annotations:
  cert-manager.io/cluster-issuer: letsencrypt
  nginx.ingress.kubernetes.io/proxy-body-size: 200m
  nginx.ingress.kubernetes.io/proxy_read_timeout: "1800"


startupProbe:
  httpGet:
    scheme: HTTP
    path: /health?whoami=amazon
    port: 11443
  initialDelaySeconds: 5
  timeoutSeconds: 5
  failureThreshold: 60
  periodSeconds: 5

readinessProbe:
  httpGet:
    scheme: HTTP
    path: /health?whoami=amazon
    port: 11443
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 10

env:
  prod:
    image: flowmapp/app-back
    host: api.flowmapp.com
    secretName: tls-flowmapp-wildcard
  staging:
    image: flowmapp/app-back-staging
    host: api.staging.flowmapp.com
    secretName: tls-back
  dev:
    image: flowmapp/app-back-dev
    host: api.dev.flowmapp.com
    secretName: tls-back
