replicas: 1

port: 80

annotations:
  cert-manager.io/cluster-issuer: letsencrypt
  nginx.ingress.kubernetes.io/configuration-snippet: |
    more_set_headers "X-Frame-Options: DENY";

startupProbe:
  httpGet:
    scheme: HTTP
    path: /
    port: 80
  initialDelaySeconds: 5
  timeoutSeconds: 5
  failureThreshold: 60
  periodSeconds: 5

readinessProbe:
  httpGet:
    scheme: HTTP
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 30

image:
  prod: flowmapp/app-front
  staging: flowmapp/app-front-staging
  dev: flowmapp/app-front-dev

host:
  prod: app.flowmapp.com
  staging: app.staging.flowmapp.com
  dev: app.dev.flowmapp.com

secretName:
  prod: tls-flowmapp-wildcard
  staging: tls-front
  dev: tls-front
