apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app
  name: health
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
  - host: health.prod.flowmapp.com
    http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 11443
  - host: health.fallback.flowmapp.com
    http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 11443
